### PR TITLE
Only call out to ec2metadata once per kafkastats execution

### LINKED ISSUE #84: Slow stats collection outside of AWS
All my Kafka brokers in AWS have no problems meeting the 30 second polling interval for kafkastats.  However, all of the brokers on physical hardware show crazy intervals between metric publishing events.
```
2019-01-16 18:22:20.856 [StatsReporter] INFO  com.pinterest.doctorkafka.stats.BrokerStatsReporter - published to kafka : {"timestamp": 1547662170130, "id": 1441
2019-01-16 18:43:50.866 [StatsReporter] INFO  com.pinterest.doctorkafka.stats.BrokerStatsReporter - published to kafka : {"timestamp": 1547663459364, "id": 1441
2019-01-16 18:56:41.630 [StatsReporter] INFO  com.pinterest.doctorkafka.stats.BrokerStatsReporter - published to kafka : {"timestamp": 1547664230872, "id": 1441
2019-01-16 19:09:32.229 [StatsReporter] INFO  com.pinterest.doctorkafka.stats.BrokerStatsReporter - published to kafka : {"timestamp": 1547665001633, "id": 1441
2019-01-16 19:22:22.797 [StatsReporter] INFO  com.pinterest.doctorkafka.stats.BrokerStatsReporter - published to kafka : {"timestamp": 1547665772231, "id": 1441
2019-01-16 19:44:07.842 [StatsReporter] INFO  com.pinterest.doctorkafka.stats.BrokerStatsReporter - published to kafka : {"timestamp": 1547667076506, "id": 1441
2019-01-16 19:56:58.609 [StatsReporter] INFO  com.pinterest.doctorkafka.stats.BrokerStatsReporter - published to kafka : {"timestamp": 1547667847848, "id": 1441
2019-01-16 20:09:49.174 [StatsReporter] INFO  com.pinterest.doctorkafka.stats.BrokerStatsReporter - published to kafka : {"timestamp": 1547668618610, "id": 1441
2019-01-16 20:22:39.883 [StatsReporter] INFO  com.pinterest.doctorkafka.stats.BrokerStatsReporter - published to kafka : {"timestamp": 1547669389176, "id": 1441
2019-01-16 20:44:25.059 [StatsReporter] INFO  com.pinterest.doctorkafka.stats.BrokerStatsReporter - published to kafka : {"timestamp": 1547670693733, "id": 1441
2019-01-16 20:57:15.843 [StatsReporter] INFO  com.pinterest.doctorkafka.stats.BrokerStatsReporter - published to kafka : {"timestamp": 1547671465064, "id": 1441
2019-01-16 21:10:06.384 [StatsReporter] INFO  com.pinterest.doctorkafka.stats.BrokerStatsReporter - published to kafka : {"timestamp": 1547672235845, "id": 1441
```
The brokers are averaging 90% idle, with reasonable amounts of free memory.  Any ideas where I should be looking to see what it's trying to do?

### PR DESCRIPTION
**Pull request by BrianGallew**
Fixes #84 

Extracts the constant host data acquisition from the run loop so it only happens once.

### CODE REVIEW

**Comment by yuyang08** [comment]
Instead of limiting to have `ec2metadata` run once, shall we fix the root cause of ec2metadata execution slowness?

AWS usually gives instance maintenance notification through "instance-action: ..." field.  In the future, We may want to leverage the "instance-action: ..." info to replace those vm instances automatically in advance, and would like to have 'ec2metadata` run regularly instead of once per kafkastats execution.

**Comment by BrianGallew** [comment]
That's a good point, but I don't know how to do it.  The fundamental problem is ec2metadata is installed by the cloud support packages, which means it exists in places that aren't AWS.  However, it's got a built-in crazy-long timeout, so it doesn't exit quickly on non-AWS hosts.

**Comment by BrianGallew** [comment]
https://github.com/aws/aws-sdk-go/issues/514 calls out AWS' decision to leave the long timeout in place.  😢

**Comment by yuyang08** [comment]
Will disabling ec2metadata execution for hosts that do not run on AWS work for your use case?  If that is the case, we can consider passing a parameter in on disabling ec2metadata execution.

**Comment by BrianGallew** [comment]
That's an idea.

**Pull request closed without merging**
